# Generated by Django 3.2.6 on 2021-09-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTabMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APIOnOff', models.BooleanField(default=True, verbose_name='接口启用状态')),
                ('UrlType', models.CharField(choices=[('POST', 'Post'), ('GET', 'Get')], default='Post', max_length=6, verbose_name='请求方式')),
                ('UrlName', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='接口名称')),
                ('CustomUrl', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='url地址')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ConditionValue', models.TextField(default='{}', verbose_name='条件匹配规则')),
                ('APIRequired', models.CharField(default='{}', max_length=5000, verbose_name='字段要求规则')),
            ],
            options={
                'verbose_name': 'Mock/路由配置表',
                'verbose_name_plural': 'Mock/路由配置表',
            },
        ),
        migrations.CreateModel(
            name='APIResponseMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('QueryValue', models.CharField(max_length=40, verbose_name='查询值')),
                ('ResponseData', models.TextField(verbose_name='响应信息数据')),
                ('CustomUrl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mockapi.routetabmock', verbose_name='关联接口')),
            ],
            options={
                'verbose_name': 'Mock/接口响应数据表',
                'verbose_name_plural': 'Mock/接口响应数据表',
                'unique_together': {('CustomUrl', 'QueryValue')},
            },
        ),
    ]
