# Generated by Django 2.2.6 on 2021-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapi', '0002_caseidmock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseidMock',
        ),
        migrations.AlterField(
            model_name='apiresponsemock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='routetabmock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
