# Generated by Django 3.2.6 on 2021-09-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapi', '0003_auto_20210916_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '接口测试页面',
                'verbose_name_plural': '接口测试页面',
            },
        ),
        migrations.AddField(
            model_name='apiresponsemock',
            name='Remarks',
            field=models.CharField(max_length=20, null=True, verbose_name='备注说明'),
        ),
        migrations.AlterField(
            model_name='apiresponsemock',
            name='QueryValue',
            field=models.CharField(db_index=True, max_length=50, verbose_name='查询值'),
        ),
        migrations.AlterField(
            model_name='apiresponsemock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='routetabmock',
            name='APIRequired',
            field=models.TextField(default='{}', verbose_name='字段要求规则'),
        ),
        migrations.AlterField(
            model_name='routetabmock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
