# Generated by Django 3.2.6 on 2021-09-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_auto_20210916_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseidmock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
